#!/bin/bash

# Script to keep SSH over VPN alive and override inactivity-timeout

function usage()
{
    echo "Usage:  autovp <server-name>"
}

if [ $# -eq 0 -o $# -lt 1 ]
then
        echo "Error: Mandatory args missing..."
        usage
        exit 1
fi

server_f=$1
autossh -M 20000 -f -N $server_f -R 1234:localhost:22 -C
ssh $server_f
